[build]
    command = "pnpm build || ( npm install pnpm && pnpm build )"
    Publish = "dist"
    functions = "functions"
[dev]
    framework = "svelte"

# [[redirects]]
#         from = "/api/*"
#         to= "/.netlify/functions/:splat"
#         status = 200
