[build]
    command = "npm run build"
    Publish = "dist"
    functions = "functions"
[dev]
    framework = "svelte"

# [[redirects]]
#         from = "/api/*"
#         to= "/.netlify/functions/:splat"
#         status = 200
